The work of the last week

diff --git a/buildroot-external/rootfs-overlay/usr/libexec/ovos-expand b/buildroot-external/rootfs-overlay/usr/libexec/ovos-expand
--- a/buildroot-external/rootfs-overlay/usr/libexec/ovos-expand
+++ b/buildroot-external/rootfs-overlay/usr/libexec/ovos-expand
@@ -35,8 +35,9 @@ echo ", +" | sfdisk --no-reread --no-tell-kernel -N "${PART_NUM}" "${DEVICE}"
 sfdisk -V "${DEVICE}"
 partx -u "${DEVICE}"
 udevadm settle
-partprobe "${DEVICE}"
 
-echo "[INFO] Resizing the homefs partition"
-resize2fs "${DEVICE_HOMEFS}"
-echo "[OK]"
+if ! systemctl start "dev-disk-by\x2dpartlabel-homefs.device"; then
+    echo "[ERROR] homefs partition not found!"
+    exit 1
+fi
+echo "[INFO] homefs partition succesfully resized"
diff --git a/buildroot-external/rootfs-overlay/usr/libexec/ovos-zram b/buildroot-external/rootfs-overlay/usr/libexec/ovos-zram
--- a/buildroot-external/rootfs-overlay/usr/libexec/ovos-zram
+++ b/buildroot-external/rootfs-overlay/usr/libexec/ovos-zram
@@ -6,15 +6,30 @@ set -e  # Exit on any command failure
 TYPE=""
 SIZE=0
 MOUNT=""
+DEVICE=""
 
 # Parse arguments
-while [ "$#" -gt 0 ]; do
-    case "$1" in
-        -t|--type) TYPE="$2"; shift 2 ;;
-        -s|--size) SIZE="$2"; shift 2 ;;
-        -m|--mount) MOUNT="$2"; shift 2 ;;
-        *) echo "Error: Invalid argument '$1'"; exit 1 ;;
+while [ "$1" != "" ]; do
+    key=$1
+    case $key in
+        -t|--type)
+            TYPE=$2
+            shift
+            ;;
+        -s|--size)
+            SIZE=$2
+            shift
+            ;;
+        -m|--mount)
+            MOUNT=$2
+            shift
+            ;;
+        *)
+            echo "[Error] $0 : Argument '$1' unknown"
+            exit 1
+            ;;
     esac
+    shift
 done
 
 # Validate Type
@@ -23,12 +38,13 @@ if [ "$TYPE" != "swap" ] && [ "$TYPE" != "fs" ]; then
     exit 1
 fi
 
-# Determine device based on type and mount
-DEVICE="/dev/zram"
+# Lookup device
 if [ "$TYPE" = "swap" ]; then
-    DEVICE+="0"
+    DEVICE="/dev/zram0"
 elif [ "$MOUNT" = "var" ]; then
-    DEVICE+="1"
+    DEVICE="/dev/zram1"
+elif [ "$MOUNT" = "tmp" ]; then
+    DEVICE="/dev/zram2"
 else
     echo "Error: No device for lookup!"
     exit 1
@@ -47,11 +63,4 @@ if [ "$TYPE" = "swap" ]; then
     mkswap -L "ovos-zramswap" "$DEVICE"
 elif [ "$TYPE" = "fs" ]; then
     mkfs.ext4 -L "ovos-$MOUNT" -O ^has_journal "$DEVICE"
-fi
-
-# Handle var mount
-if [ "$MOUNT" = "var" ]; then
-    VAR_DIR="/mnt/data/var"
-    [ ! -d "$VAR_DIR" ] && mkdir -p "$VAR_DIR" && cp -af /var/* "$VAR_DIR"
-    cp -af "$VAR_DIR"/* "$DEVICE"
 fi
